#!/usr/bin/env python3

#Generated by AI, edited by Ye
"""
USB Keyboard to GPIO Output Translator
Reads keystrokes from a USB keyboard and toggles GPIO pins accordingly.
Tested on Raspberry Pi OS with Python 3.
"""

import RPi.GPIO as GPIO
from evdev import InputDevice, categorize, ecodes
import sys
import os
import time
import threading

# Track which keys are currently held 
held_keys = set()

# --- CONFIGURATION ---
# Map keys to GPIO pins

# Keymaping manually added by Ye
KEY_TO_GPIO = {
    ecodes.KEY_W: 2,    #Rot
    ecodes.KEY_A: 3,    #MV
    ecodes.KEY_S: 4,    #Down
    ecodes.KEY_D: 14,   #MV
    ecodes.KEY_R: 15,   #Hold

    ecodes.KEY_I: 17,
    ecodes.KEY_J: 27,
    ecodes.KEY_K: 22,
    ecodes.KEY_L: 23,
    ecodes.KEY_P: 24,
}

# --- SETUP GPIO ---
GPIO.setmode(GPIO.BCM)
for pin in KEY_TO_GPIO.values():
    GPIO.setup(pin, GPIO.OUT)
    GPIO.output(pin, GPIO.HIGH)
    
def find_keyboard():
    for filename in os.listdir('/dev/input'):
        if not filename.startswith('event'):
            continue

        path = os.path.join('/dev/input', filename)

        try:
            dev = InputDevice(path)
        except FileNotFoundError:
            continue

        print(path, "->", dev.name)

        # Check whether device actually supports keyboard keys
        capabilities = dev.capabilities()

        if ecodes.EV_KEY in capabilities:
            keys = capabilities[ecodes.EV_KEY]

            if ecodes.KEY_W in keys:
                print("FOUND KEYBOARD:", path)
                return dev

    return None

# Track which keys are currently held
held_keys = set()

def pulse_pin(pin, keycode):
    """Pulse a GPIO pin while the corresponding key is held."""
    while keycode in held_keys:
        GPIO.output(pin, GPIO.LOW)
        GPIO.output(pin, GPIO.HIGH)

        # Check again in case key was released
        if keycode not in held_keys:
            break
        time.sleep(0.05)

    # Leave the pin HIGH after release
    GPIO.output(pin, GPIO.HIGH)


keyboard = find_keyboard()

try:
    for event in keyboard.read_loop():
        if event.type == ecodes.EV_KEY:

            if event.code in KEY_TO_GPIO:
                pin = KEY_TO_GPIO[event.code]

                if event.value == 1:  # Key pressed
                    # Ignore repeated key events
                    if event.code not in held_keys:
                        held_keys.add(event.code)

                        print(f"Key {event.code} pressed -> GPIO{pin} pulsing")

                        thread = threading.Thread(
                            target=pulse_pin,
                            args=(pin, event.code),
                            daemon=True
                        )
                        thread.start()

                elif event.value == 0:  # Key released
                    held_keys.discard(event.code)

                    GPIO.output(pin, GPIO.HIGH)
                    print(f"Key {event.code} released -> GPIO{pin} HIGH")

except KeyboardInterrupt:
    print("\nExiting...")

finally:
    held_keys.clear()
    GPIO.cleanup()

